In [9]:
import pandas as pd 



# read video_errors.csv and video_metadata.csv

video_errors = pd.read_csv('video_errors.csv')
video_metadata = pd.read_csv('video_metadata.csv')


# merge the two dataframes on the 'video_id' column
merged_df = pd.merge(video_errors, video_metadata, on='youtube_url', how='outer')

merged_df

,youtube_url,error,title,description,caption,caption_language,publish_date,rating,channel_id,channel_url,thumbnail_url,channel_name,views,keywords,duration,video_path
0,https://www.youtube.com/shorts/-M7VdrQpWps,NaN,Spin Lightning,NaN,NaN,NaN,2024-07-16 07:20:51-07:00,NaN,UCOhFXcmfy8T11SgYFIrzY8Q,https://www.youtube.com/channel/UCOhFXcmfy8T11...,https://i.ytimg.com/vi/-M7VdrQpWps/sddefault.j...,Ideas 1+1,70431015.0,[],NaN,videos/Spin Lightning.mp4
1,https://www.youtube.com/shorts/-Tf9VMl4krk,NaN,Monster Energy works better than Vinegar | Rus...,NaN,NaN,NaN,2024-08-19 14:47:17-07:00,NaN,UCK02oH_1vqL4VrUBEFXEUcA,https://www.youtube.com/channel/UCK02oH_1vqL4V...,https://i.ytimg.com/vi/-Tf9VMl4krk/sddefault.j...,Menard Metal Craft,20914321.0,"['Restoration', 'Science', 'ASMR', 'oddly sati...",NaN,videos/Monster Energy works better than Vinega...
2,https://www.youtube.com/shorts/-o7pVduTGVs,NaN,Now He’ll Never Leave😭,ill be over here with my broken back🫠,"1\r\n00:00:00,719 --> 00:00:04,600\r\nhey Mom ...",a.en,2024-05-23 18:54:30-07:00,NaN,UC1WbRuMMzbzUfBG65x1FmXQ,https://www.youtube.com/channel/UC1WbRuMMzbzUf...,https://i.ytimg.com/vi/-o7pVduTGVs/sddefault.j...,Peet Montzingo,320974272.0,"['peet montzingo', 'monzingo', 'mozingo', 'pet...",NaN,videos/Now He’ll Never Leave😭.mp4
3,https://www.youtube.com/shorts/0-ugjds_Rz8,NaN,Stationary items that every student must have🦋...,NaN,"1\r\n00:00:00,000 --> 00:00:09,030\r\ncómo hac...",a.es,2022-06-30 04:51:47-07:00,NaN,UCIJ3_6Mby5AqCfGWM-XSk2w,https://www.youtube.com/channel/UCIJ3_6Mby5AqC...,https://i.ytimg.com/vi/0-ugjds_Rz8/sd2.jpg?sqp...,초코 민트 choco mint,1331558.0,[],16.67,videos/Stationary items that every student mus...
4,https://www.youtube.com/shorts/0cKKHnAmncI,NaN,錯覺系列 箭頭方向 都一樣!? 視覺欺騙 有趣 好玩 科學 現象,利用視角與形狀的角度差來形成....\r\n\r\n喜歡我們系列的影片可以加LINE@ 搜尋...,NaN,NaN,2018-05-22 06:54:07-07:00,NaN,UClf9mmmtB6qdsPH-UNyAcnA,https://www.youtube.com/channel/UClf9mmmtB6qds...,https://i.ytimg.com/vi/0cKKHnAmncI/sd2.jpg?sqp...,JackWang,1168.0,"['視覺', '幻覺', '錯覺', '科學', '光學', '2018', '設計', '...",42.98,videos/錯覺系列 箭頭方向 都一樣!? 視覺欺騙 有趣 好玩 科學 現象.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,https://youtube.com/shorts/ly70cIZgrRA,NaN,This is why he owns the hotel,NaN,NaN,NaN,2024-10-08 10:01:38-07:00,NaN,UCC2lbKruS3-22iTD_1fe_MQ,https://www.youtube.com/channel/UCC2lbKruS3-22...,https://i.ytimg.com/vi/ly70cIZgrRA/sd2.jpg?sqp...,NXCRE,32959150.0,[],30.93,videos/This is why he owns the hotel.mp4
288,https://youtube.com/shorts/rCW1aGpFrJg,NaN,Limpando a escada rolante,NaN,"1\r\n00:00:05,090 --> 00:00:14,259\r\n[Music]\...",a.en,2024-01-27 16:33:52-08:00,NaN,UCtiddfzHXNevG-yYe5vc_4Q,https://www.youtube.com/channel/UCtiddfzHXNevG...,https://i.ytimg.com/vi/rCW1aGpFrJg/sd2.jpg?sqp...,Spider Slack,324516640.0,[],58.82,videos/Limpando a escada rolante.mp4
289,https://youtube.com/shorts/u2HvKEGq3Ik,u2HvKEGq3Ik is unavailable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,https://youtube.com/shorts/vXUZpRRrIBU,NaN,Sour Family Sour Gummy Lemon Challenge! 🍋,#viral #gummy #challenge,"1\r\n00:00:00,120 --> 00:00:02,599\r\ntiny\r\n...",a.en,2024-04-27 22:00:33-07:00,NaN,UCm4FUt0uVITowfThQhs0NNQ,https://www.youtube.com/channel/UCm4FUt0uVITow...,https://i.ytimg.com/vi/vXUZpRRrIBU/sd2.jpg?sqp...,DrewMe2Jesus,125974312.0,"['sour king', 'sour king drew', 'sourking', 's...",30.32,videos/Sour Family Sour Gummy Lemon Challenge!...
291,https://youtube.com/shorts/vz9D4nqhTyk,NaN,When you and the boys were caught up late at a...,NaN,NaN,NaN,2023-11-24 10:25:38-08:00,NaN,UCc0AvMpTPtEsgN7_IRZlrKQ,https://www.youtube.com/channel/UCc0AvMpTPtEsg...,https://i.ytimg.com/vi/vz9D4nqhTyk/sd2.jpg?sqp...,Nolan Hernandez,25617386.0,[],37.68,videos/When you and the boys were caught up la...

In [10]:
merged_df

# extract the id from youtube_url "https://www.youtube.com/shorts/-o7pVduTGVs"
merged_df['video_id'] = merged_df["youtube_url"].str.strip().str.split("/").str[-1].apply(lambda x: f'{x}')
merged_df['video_id'] 
# Create new video_path column where its f"videos_full/{video_id}.mp4"

merged_df['video_path'] = merged_df['video_id'].apply(lambda x: f"videos_full/{x}.mp4")

In [11]:
merged_df

,youtube_url,error,title,description,caption,caption_language,publish_date,rating,channel_id,channel_url,thumbnail_url,channel_name,views,keywords,duration,video_path,video_id
0,https://www.youtube.com/shorts/-M7VdrQpWps,NaN,Spin Lightning,NaN,NaN,NaN,2024-07-16 07:20:51-07:00,NaN,UCOhFXcmfy8T11SgYFIrzY8Q,https://www.youtube.com/channel/UCOhFXcmfy8T11...,https://i.ytimg.com/vi/-M7VdrQpWps/sddefault.j...,Ideas 1+1,70431015.0,[],NaN,videos_full/-M7VdrQpWps.mp4,-M7VdrQpWps
1,https://www.youtube.com/shorts/-Tf9VMl4krk,NaN,Monster Energy works better than Vinegar | Rus...,NaN,NaN,NaN,2024-08-19 14:47:17-07:00,NaN,UCK02oH_1vqL4VrUBEFXEUcA,https://www.youtube.com/channel/UCK02oH_1vqL4V...,https://i.ytimg.com/vi/-Tf9VMl4krk/sddefault.j...,Menard Metal Craft,20914321.0,"['Restoration', 'Science', 'ASMR', 'oddly sati...",NaN,videos_full/-Tf9VMl4krk.mp4,-Tf9VMl4krk
2,https://www.youtube.com/shorts/-o7pVduTGVs,NaN,Now He’ll Never Leave😭,ill be over here with my broken back🫠,"1\r\n00:00:00,719 --> 00:00:04,600\r\nhey Mom ...",a.en,2024-05-23 18:54:30-07:00,NaN,UC1WbRuMMzbzUfBG65x1FmXQ,https://www.youtube.com/channel/UC1WbRuMMzbzUf...,https://i.ytimg.com/vi/-o7pVduTGVs/sddefault.j...,Peet Montzingo,320974272.0,"['peet montzingo', 'monzingo', 'mozingo', 'pet...",NaN,videos_full/-o7pVduTGVs.mp4,-o7pVduTGVs
3,https://www.youtube.com/shorts/0-ugjds_Rz8,NaN,Stationary items that every student must have🦋...,NaN,"1\r\n00:00:00,000 --> 00:00:09,030\r\ncómo hac...",a.es,2022-06-30 04:51:47-07:00,NaN,UCIJ3_6Mby5AqCfGWM-XSk2w,https://www.youtube.com/channel/UCIJ3_6Mby5AqC...,https://i.ytimg.com/vi/0-ugjds_Rz8/sd2.jpg?sqp...,초코 민트 choco mint,1331558.0,[],16.67,videos_full/0-ugjds_Rz8.mp4,0-ugjds_Rz8
4,https://www.youtube.com/shorts/0cKKHnAmncI,NaN,錯覺系列 箭頭方向 都一樣!? 視覺欺騙 有趣 好玩 科學 現象,利用視角與形狀的角度差來形成....\r\n\r\n喜歡我們系列的影片可以加LINE@ 搜尋...,NaN,NaN,2018-05-22 06:54:07-07:00,NaN,UClf9mmmtB6qdsPH-UNyAcnA,https://www.youtube.com/channel/UClf9mmmtB6qds...,https://i.ytimg.com/vi/0cKKHnAmncI/sd2.jpg?sqp...,JackWang,1168.0,"['視覺', '幻覺', '錯覺', '科學', '光學', '2018', '設計', '...",42.98,videos_full/0cKKHnAmncI.mp4,0cKKHnAmncI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,https://youtube.com/shorts/ly70cIZgrRA,NaN,This is why he owns the hotel,NaN,NaN,NaN,2024-10-08 10:01:38-07:00,NaN,UCC2lbKruS3-22iTD_1fe_MQ,https://www.youtube.com/channel/UCC2lbKruS3-22...,https://i.ytimg.com/vi/ly70cIZgrRA/sd2.jpg?sqp...,NXCRE,32959150.0,[],30.93,videos_full/ly70cIZgrRA.mp4,ly70cIZgrRA
288,https://youtube.com/shorts/rCW1aGpFrJg,NaN,Limpando a escada rolante,NaN,"1\r\n00:00:05,090 --> 00:00:14,259\r\n[Music]\...",a.en,2024-01-27 16:33:52-08:00,NaN,UCtiddfzHXNevG-yYe5vc_4Q,https://www.youtube.com/channel/UCtiddfzHXNevG...,https://i.ytimg.com/vi/rCW1aGpFrJg/sd2.jpg?sqp...,Spider Slack,324516640.0,[],58.82,videos_full/rCW1aGpFrJg.mp4,rCW1aGpFrJg
289,https://youtube.com/shorts/u2HvKEGq3Ik,u2HvKEGq3Ik is unavailable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,videos_full/u2HvKEGq3Ik.mp4,u2HvKEGq3Ik
290,https://youtube.com/shorts/vXUZpRRrIBU,NaN,Sour Family Sour Gummy Lemon Challenge! 🍋,#viral #gummy #challenge,"1\r\n00:00:00,120 --> 00:00:02,599\r\ntiny\r\n...",a.en,2024-04-27 22:00:33-07:00,NaN,UCm4FUt0uVITowfThQhs0NNQ,https://www.youtube.com/channel/UCm4FUt0uVITow...,https://i.ytimg.com/vi/vXUZpRRrIBU/sd2.jpg?sqp...,DrewMe2Jesus,125974312.0,"['sour king', 'sour king drew', 'sourking', 's...",30.32,videos_full/vXUZpRRrIBU.mp4,vXUZpRRrIBU
291,https://youtube.com/shorts/vz9D4nqhTyk,NaN,When you and the boys were caught up late at a...,NaN,NaN,NaN,2023-11-24 10:25:38-08:00,NaN,UCc0AvMpTPtEsgN7_IRZlrKQ,https://www.youtube.com/channel/UCc0AvMpTPtEsg...,https://i.ytimg.com/vi/vz9D4nqhTyk/sd2.jpg?sqp...,Nolan Hernandez,25617386.0,[],37.68,videos_full/vz9D4nqhTyk.mp4,vz9D4nqhTyk

In [13]:
# save as video_full_metadata.csv
merged_df.to_csv('video_full_metadata.csv', index=False, encoding='utf-8-sig')